---
abstract: "Signs requests using Amazon's Signature Version 4."
author:
  - 'Charles A. Wimmer <charles@wimmer.net>'
build_requires:
  Dist::Zilla::App::Command::cover: 0
  File::Slurp: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Compare: 0
  Pod::Coverage::TrustPod: 0
  TAP::Formatter::JUnit: 0
  TAP::Harness::JUnit: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-SignatureVersion4
requires:
  Data::Dumper: 0
  Digest::SHA: 0
  HTTP::Date: 0
  MooseX::App: 0
  POSIX: 0
  URI::Encode: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/cwimmer/Net-Amazon-SignatureVersion4.git
version: 0.003
